# Generated by Django 3.0.4 on 2020-03-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20200313_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='per',
            field=models.IntegerField(default=1),
        ),
    ]
