# Generated by Django 3.0.4 on 2020-03-17 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20200316_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='last_rate_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 11, 2, 24, 386868)),
        ),
    ]
