# Generated by Django 3.0.4 on 2020-03-17 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_currency_last_rate_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='last_rate_update',
        ),
        migrations.AddField(
            model_name='currency',
            name='latest_rate_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 12, 46, 33, 561375)),
        ),
    ]
