# Generated by Django 3.0.4 on 2020-03-18 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_auto_20200317_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 11, 52, 21, 26210)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='latest_rate_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 11, 52, 21, 26210)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5),
        ),
    ]
