# Generated by Django 3.0.4 on 2020-03-19 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_auto_20200319_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date_valid',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 8, 9, 53, 633471, tzinfo=utc)),
        ),
    ]
